### ISSUE TITLE
Connection drop on switching to next song

### ISSUE THREAD

**Issue by vadimyer** [fgergo/boringstreamer#1]
Tested in Chrome, Firefox.

The server itself seems to behave fine (logs DC message, continuing to play things, accepting connections).

I guess it thinks for a moment,  that the stream has ended - and closes the connection.

Probably some buffering issue?

**Comment by fgergo** [comment]
@vadimyer thanks for the report!
The latest version has been working for me ok, for a long time. Earlier versions had this bug, with some very messeg up mp3 files though.

It could be a software issue, though more context will help pin down the root cause. Could you please provide more detail:
1. what do you mean by connection drop?  What do you expect vs. what do you see? Is the browser tab in the front or in the background? Is the issue after computer woken up after a sleep/hibernation?
2. is the issue reproducible? If yes could you please run:
boringstreamer -v directory_with_mp3_files -debug
and share the log file?
If it depends on the mp3 files, can you share the files?
3. boringstreamer version? (Is it c678ef8 ?
4. server OS platform versions?
5. browser OS+browser versions?
6. network medium types between server and browser? (e.g. (cable|wifi|mobile) or no network, boringstreamer running locally?)
7. anything else in particular? (e.g. Is the network stable for other programs between the server and the client computer?)

**Comment by vadimyer** [comment]
I forgot to mention, this issue isn't happening on every song switch, it's more like random.
I've tested it on clients: Chrome latest, Firefox latest, Java client (some radio mod for Minecraft). OS is Win 10 Pro.
On 2 servers: Debian 8+, Go 1.7.5 linux/amd64, Go 1.8.rc3 linux/amd64.
I'll take a log into it with debug a bit later.

**Comment by vadimyer** [comment]
I've ran with debug, here's the output on trying to switch to third song:

```
$ boringstreamer -max 500 -addr :9876 -v -r /home/vadimyer7/radio -debug
Looking for files available from "/home/vadimyer7/radio" ...
Waiting for connections on :9876
Next: /home/vadimyer7/radio/Roxette - Real Sugar.mp3
Now playing: /home/vadimyer7/radio/Roxette - Real Sugar.mp3
Next: /home/vadimyer7/radio/Camera Obscura - The Sweetest Thing.mp3
info: mp3 decode msg: 2017/01/29 18:51:03 Skipped 4096 bytes
New connection (qid: 0), streaming to 1 connections, at Jan 29 18:51:09
info: mp3 decode msg: 2017/01/29 18:54:18 Skipped 62464 bytes
Now playing: /home/vadimyer7/radio/Camera Obscura - The Sweetest Thing.mp3
Next: /home/vadimyer7/radio/Two Door Cinema Club - Bad Decisions.mp3
2017/01/29 18:56:17 Connection exited, qid: 0, error write tcp 91.107.108.196:9876->5.167.162.29:53171: write: broken pipe. Now streaming to 0 connections.
New connection (qid: 0), streaming to 1 connections, at Jan 29 18:56:20
Now playing: /home/vadimyer7/radio/Two Door Cinema Club - Bad Decisions.mp3
Next: /home/vadimyer7/radio/Niklas Thal - Winter Symphony (Original Mix).mp3
info: mp3 decode msg: 2017/01/29 18:58:40 Skipped 21 bytes
info: mp3 decode msg: 2017/01/29 18:58:40 Skipped 30 bytes
info: mp3 decode msg: 2017/01/29 18:58:40 Skipped 986 bytes
2017/01/29 18:58:48 Connection exited, qid: 0, error timeout: 4s. Now streaming to 0 connections.
^C
```

**Comment by fgergo** [comment]
ok, thanks! Are you sure you are running the latest commit?

**Comment by vadimyer** [comment]
Yes absolutely =) It didn't update for a long time, I've `go get` it just yesterday.

**Comment by fgergo** [comment]
Until I can reproduce the issue, I can only guess at the moment: I changed the http timeout from 4s to 44s. Please take a look when you'll have time.

**Comment by vadimyer** [comment]
Thanks, testing it.

**Comment by vadimyer** [comment]
Oh BTW, race detector found a race on line 331.

**Comment by fgergo** [comment]
uhh, thanks! I did not expect that. Will take a look later.

**Comment by fgergo** [comment]
​Race fixed (22e0a12c2). Will double-check later, though it'd be nice if
you could also check.

**Comment by vadimyer** [comment]
Okay, testing it now. Thanks!
If it will play 10 songs without DC, I think the fix works. Though it still prints those "Skipped ... bytes" messages when switching over songs.
I guess you can revert the commit changing http timeout back =)

**Comment by vadimyer** [comment]
Sadly the fix doesn't work =(
Broke on switching to second song:

```
$ boringstreamer -max 500 -addr :9876 -v -r /home/vadimyer7/radio -debug
Looking for files available from "/home/vadimyer7/radio" ...
Waiting for connections on :9876
Next: /home/vadimyer7/radio/▒2 - mp3
Now playing: /home/vadimyer7/radio/▒2 - mp3
Next: /home/vadimyer7/radio/ONE OK ROCK - Bombs Away.mp3
New connection (qid: 0), streaming to 1 connections, at Jan 30 01:44:12
Now playing: /home/vadimyer7/radio/ONE OK ROCK - Bombs Away.mp3
Next: /home/vadimyer7/radio/The Ready Set x Kaptan - Take You There.mp3
info: mp3 decode msg: 2017/01/30 01:47:38 Skipped 21 bytes
info: mp3 decode msg: 2017/01/30 01:47:38 Skipped 1979 bytes
Now playing: /home/vadimyer7/radio/The Ready Set x Kaptan - Take You There.mp3
Next: /home/vadimyer7/radio/OneRepublic - Let#039;s Hurt Tonight.mp3
info: mp3 decode msg: 2017/01/30 01:52:02 Skipped 21 bytes
info: mp3 decode msg: 2017/01/30 01:52:02 Skipped 4436 bytes
info: mp3 decode msg: 2017/01/30 01:52:02 Skipped 29 bytes
info: mp3 decode msg: 2017/01/30 01:52:02 Skipped 27 bytes
info: mp3 decode msg: 2017/01/30 01:52:02 Skipped 95650 bytes
2017/01/30 01:52:52 Connection exited, qid: 0, error timeout: 44s. Now streaming to 0 connections.
```

**Comment by fgergo** [comment]
thanks, that's strange.

"Skipped" messages are for information only. If the mp3 file has any other bits than mp3 frames, they will be skipped. BS logs this information. Depending on your mp3 file sources, some files have id3 tags in them. They are not mp3 frames, they are skipped.
Also if the mp3 data is corrupt, they are also skipped.

What is the exact version of your browser?
Can you please check streaming with firefox?
Can you check locally on the debian server or is it headless?
Could you also please check 192.241.166.102:4444/ if your chrome or firefox stops playing music?

If the error comes up after a few songs, could you also please check this theory:
Maybe chrome on windows 10 is throttling background tabs. I haven't seen this behaviour just yet, I've read recently that chrome will start to throttle background tabs more aggressively. Could you please check with the playing tab in the foreground?

Also: I am not sure what you mean by "DC", could you please clarify?

**Comment by vadimyer** [comment]
Chrome 55.0.2883.87 m (64-bit).
My server boxes are headless, soz.
I've checked you stream and got DC'ed (disconnected) on switching to third or fourth song just recently.

**Comment by fgergo** [comment]
thanks.
Could you also please check fm.acko.net:1337 that's an icecast server not controlled by me.
If that server won't disconnect, then boringstreamer can do something better, but if it disconnects as well, the root cause is out of the streaming software's control.

Also: I'd be interested if you could please check boringstreamer with the playing tab in the foreground for a few songs.

**Comment by vadimyer** [comment]
Oh I don't have issues with Icecast servers.
The thing I'm trying to use boringstreamer for is a radio for our Minecraft network.
It has radios in-game which default to some popular Icecast-powered station and work flawlessly 24/7 for everyone including me.

**Comment by vadimyer** [comment]
The only thing I can think of that causes this issue is if a song have lots of "wrong bytes" (as you've said it's decided by a third-party mp3 decoder) which "leak" somehow to the client causing it to disconnect because it thinks the data is not an audio and invokes a disconnect.

**Comment by fgergo** [comment]
ok, but my browsers never disconnect and yours disconnected on the ip
address i shared with you. If thats an issue my browsers should disconnect
as well.

I regularly use windows, linux, 4 different hw platforms both as servers
and clients sometimes via cell data network to android chrome on my phone
or stock ios browser on ipad. no disconnect.

i rather suspect something more windows10 specific behaviour, which
boringstreamer or more specifically the go http libs won't handle as an
icecast server would.

are the minecraft clients disconnecting as well?

**Comment by vadimyer** [comment]
Minecraft client disconnected multiple times on my songs (I've tested with 2 different servers), but I'm playing your stream right now there, already like 5-10+ songs passed and still without any disconnect.

**Comment by vadimyer** [comment]
I've tested it again in Chrome with some throttling enabled in dev tools, first turned on GPRS option, got totally no sound for a few seconds, and switched back to no throttling and got sound back, but after a few seconds the stream disconnected with this error in console:

```
GET http://192.241.166.102:4444/ net::ERR_INVALID_CHUNKED_ENCODING
```

**Comment by fgergo** [comment]
ok, i propose you share your "disconnecting" 3-5 mp3 files somewhere for me
to put behind my bs instance.

**Comment by fgergo** [comment]
yes, network has to provide at least the mp3 bitrate (160-320kbps depending
on the files) otherwise the browser definitely gives up and disconnects...

**Comment by vadimyer** [comment]
BTW are these headers actually set up:

```
        w.WriteHeader(http.StatusOK)
	w.Header().Set("Date", now.Format(http.TimeFormat))
	w.Header().Set("Connection", "Keep-Alive")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Content-Type", "audio/mpeg")
	w.Header().Set("Server", "BoringStreamer/4.0")
```

Cause I don't have them present in Chrome/Firefox when I connect to either yours or mine station.
Checked with my files now, after the 1.mp3 file ends the 2.mp3 gets stuck and DCs the client, here's the link to the files: https://s.vadimyer.com/mp3s.zip

**Comment by fgergo** [comment]
1.mp3 and 2.mp3 are up at http://192.241.166.102:5555/

**Comment by vadimyer** [comment]
Sigh, I got DCed in Minecraft from http://192.241.166.102:5555/, after 2.mp3 had played.
In Chrome it DCed after 1.mp3.
Thanks for you time on this.

**Comment by fgergo** [comment]
My browser disconnects on these 2 mp3s as well, after both 1.mp3 and 2.mp3.
Ok, now this is a reproducer. Thanks!

I'll be back in a few hours and will take a closer look at these mp3 files.

I can see the headers set with telerik.com/fiddler.

(fyi: I stress tested boringstreamer with >800 concurrent connections with
a cheap DO vps. For ~1000 concurrent streaming clients the vps ran out of
RAM because the clients were running on the vps as well, BS was barely
using any RAM, but a significant part of CPU.)

**Comment by vadimyer** [comment]
Yeah well but could you also please check the headers at Chrome directly? There's clearly no `Cache-Control, Connection and Server` headers.

**Comment by fgergo** [comment]
@vadimyer:
Workaround until I figure out a fix: stream files with the same sample rate for 1 running boringstreamer.

Details if you are interested:
chrome://media-internals/ to the rescue.
The root cause of the issue is that browsers and probably other HLS players cannot cope with sample rate change during a HLS streaming session.
At the moment I see at least 2 resolutions:
1. decode and re-encode all mp3 files to 1 designated sample rate
pros:
- probably the "smoothest" resolution, if I find a suitable mp3 go encoder package
cons:
- decode and re-encode sounds like degraded quality, though 1. it's mp3, soooo..., 2. all streamers probably do that, sooo....
- it's probably significantly more CPU intensive, than current implementation

2. somehow get the hls players to acknowladge sample rate change when needed.
pros:
- no sound quality change
- does not need more resources than current version
cons:
- I don't know if it's feasible.

**Comment by vadimyer** [comment]
Thanks for the insight.
First option is definitely adequate, I think it should be there by default, since it's actually a streamer.
If it will take time for you, I might actually rewrite bits to use ffmpeg for encode/decode part.
I really don't have other choices, since I need to integrate the whole thing tightly into the service and implement some features, which would be easier for me to do based on this one lib.

**Comment by fgergo** [comment]
My motivation for boringstreamer was to avoid the whole "install this, install that, configure this" current streamer situation.
I wanted to have a single binary for all maintstream platforms (linux, windows) +sensible default streaming behavior without any configuration burden, to listen to my own music collection.
Later I could see that there are other sensible use cases for boringstreamer, hence the possibility to streamer date received on the standard input. (See "To stream from standard input: boringstreamer -" -h flag)
You probably want that at the moment.

**Comment by fgergo** [comment]
Added BUGS section with workarounds to both readme.md and to source.
